FROM python:3.10-slim

RUN pip install \
  dagster \
  dagster-docker \
  dagster-postgres \
  dagster-webserver

WORKDIR /opt/dagster/app

COPY ./repo.py /opt/dagster/app/

EXPOSE 4000
CMD ["dagster", "api", "grpc", "--python-file", "repo.py", "--host", "0.0.0.0", "--port", "4000"]
